name: Build Lib

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar NDK correto
        run: sdkmanager --install "ndk;21.4.7075529"

      - name: Compilar com ndk-build
        run: |
          export NDK_HOME=$ANDROID_SDK_ROOT/ndk/21.4.7075529
          $NDK_HOME/ndk-build \
            NDK_PROJECT_PATH=null \
            APP_BUILD_SCRIPT=./Android.mk \
            NDK_APPLICATION_MK=./Application.mk \
            NDK_LIBS_OUT=./libs \
            NDK_OUT=./obj

      - name: Guardar .so gerado
        uses: actions/upload-artifact@v4
        with:
          name: compiled-so
          path: libs/**/*.so
